### PR TITLE
Webpack build improvements

### LINKED ISSUE #26: Error: net::ERR_CONNECTION_REFUSED on yarn build
When running `yarn build`, I'm getting this error:
`UnhandledPromiseRejectionWarning: Error: net::ERR_CONNECTION_REFUSED at http://localhost:8505`

any idea what would cause this?

### PR DESCRIPTION
**Pull request by manuelbieh**
## Description / What does this PR do?

- Removes some garbage (console output, test variables that should have never landed in master, etc.)
- Fixes #26 (hopefully 😉)
- Adds `analyze` script to analyze webpack bundle size

## Related Issue / Story / Ticket

- #26

### CODE REVIEW

File: scripts/build.js [hunk 1]
```diff
@@ -28,18 +28,20 @@ const generateStaticHTML = async () => {
             const pageContent = await page.content();
             fs.writeFileSync(`${paths.clientBuild}/index.html`, pageContent);
             await browser.close();
-            process.exit();
+            // process.exit();
```
Comment (manuelbieh) [inline scripts/build.js]: remove comment
